//file:noinspection GrDeprecatedAPIUsage
buildscript {
    ext {
        kotlin_version = '2.4.10'
        application_id = 'store.anartist.anartiststore'
    }
    repositories {
        google()
        //noinspection GrUnresolvedAccess
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.3.1'
        classpath 'com.google.gms:google-services:4.5.0'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.7'
        //noinspection GrUnresolvedAccess
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

//noinspection GrDeprecatedAPIUsage
rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
