name: Flutter Android CI & Quality
on: [ push ]

jobs:
  check-code-quality-and-tests:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get packages
        run: flutter pub get

      - name: Check format errors
        run: dart format --set-exit-if-changed .

      - name: Check lint errors
        run: flutter analyze .

      - name: Run tests with coverage and random order
        run: flutter test --coverage --test-randomize-ordering-seed random

      - name: Very Good Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2.1.0
        with:
          min_coverage: 29

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Turskyi/anartiststore

  build_apk:
    name: Build Flutter (Android)
    needs: [ check-code-quality-and-tests ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Write google-services.json file
        run: |
          cd android/app
          echo $GOOGLE_SERVICES | base64 -d > google-services.json
        shell: bash
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}

      - name: Write key.properties file
        run: |
          echo $KEY_PROPERTIES | base64 -d > android/key.properties
        shell: bash
        env:
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}

      - name: Create keystore folder
        run: mkdir -p android/keystore

      - name: Write anartiststore_release.keystore file
        env:
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
        run: |
          echo $RELEASE_KEYSTORE | base64 --decode > android/keystore/anartiststore_release.keystore

      - name: Write anartiststore_debug.keystore file
        run: |
          echo $DEBUG_KEYSTORE | base64 -d > android/keystore/anartiststore_debug.keystore
        shell: bash
        env:
          DEBUG_KEYSTORE: ${{ secrets.DEBUG_KEYSTORE }}

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get

      - run: flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-build
          path: build/app/outputs/apk/release/app-release.apk

  beta_apk:
    name: Upload Android Beta version to Firebase App Distribution
    needs: [ build_apk ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: apk-build
      - name: Display structure of downloaded files
        run: ls -R
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.FIREBASE_SERVICE_ACCOUNT_CREDENTIALS}}
          groups: testers
          file: app-release.apk
